version: 2.1
orbs:
  cypress: cypress-io/cypress@1.3.0
workflows:
  commit:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
        store_artifacts: true
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
        store_artifacts: true